const address='5cQReyzgJQbtbGLvkm1vN9GDGFBWzcAC6TDprBwzVVjL';
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
let toastTimer;
function notify(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),4000);}
document.getElementById('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(address);notify('Full token address copied.');}catch{notify('Copy unavailable. Open UsePaid to copy the address.');}});
document.getElementById('payout').addEventListener('input',event=>{const n=Number(event.target.value);const valid=event.target.value!==''&&Number.isFinite(n)&&n>=0&&n<=1e9;document.getElementById('buyback-result').textContent=valid?money.format(n*.6):'—';document.getElementById('growth-result').textContent=valid?money.format(n*.4):'—';});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelectorAll('[data-category]').forEach(card=>card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter);}));
const briefs={"code": {"title": "Build something with AI.", "description": "The contribution is the idea and the work, not just a change to this website. Bring a tool, agent, experiment, research project, or open-source improvement.", "items": ["Explain what you want to build, who it helps, and what you have learned so far.", "Share a demo, research notes, or a repository others can inspect and build on.", "If you want funding or collaborators, propose a scope, milestones, and budget for discussion."]}, "creative": {"title": "Make optimism contagious.", "description": "Help people understand, imagine, and experiment with AI through original creative work.", "items": ["Create memes, video, interactive art, explainers, or a new format entirely.", "Share the process, editable assets where possible, and appropriate creator credits.", "Propose how others could remix or extend your work."]}, "community": {"title": "Find the people shipping.", "description": "Connect builders and investors around work worth exploring. Curate projects, share knowledge, or organise a small collaboration.", "items": ["Feature useful AI projects with source links and creator credit.", "Host a demo session, publish a research roundup, or connect contributors with complementary skills.", "Describe the community need and a practical first step; discuss any proposed funding openly."]}};
const dialog=document.getElementById('mission-dialog');
document.querySelectorAll('[data-mission]').forEach(b=>b.addEventListener('click',()=>{const brief=briefs[b.dataset.mission];document.getElementById('mission-title').textContent=brief.title;document.getElementById('mission-description').textContent=brief.description;const list=document.getElementById('mission-deliverables');list.replaceChildren(...brief.items.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));dialog.showModal();}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
const canvas=document.getElementById('poster'),ctx=canvas.getContext('2d'),headline=document.getElementById('headline');
headline.value='THE FUTURE\nIS A GROUP\nPROJECT.';
let theme='acid';
function renderPoster(){const colors={acid:['#d3fa49','#14180c'],paper:['#f1f0e7','#161a12'],dark:['#191e14','#d3fa49']};const [bg,fg]=colors[theme];ctx.fillStyle=bg;ctx.fillRect(0,0,1080,1080);ctx.strokeStyle=fg;ctx.globalAlpha=.13;ctx.lineWidth=1;for(let n=40;n<1080;n+=50){ctx.beginPath();ctx.moveTo(n,0);ctx.lineTo(n,1080);ctx.stroke();ctx.beginPath();ctx.moveTo(0,n);ctx.lineTo(1080,n);ctx.stroke();}ctx.globalAlpha=1;ctx.fillStyle=fg;ctx.font='700 36px "DM Sans", Arial';ctx.fillText('↗↗  AI/MAXXI',65,88);ctx.font='20px "IBM Plex Mono", monospace';ctx.textAlign='right';ctx.fillText('COMMUNITY TRANSMISSION',1015,85);ctx.textAlign='left';const text=headline.value.trim()||'BUILD THE FUTURE.';let size=155,lines=[];for(;size>=50;size-=5){ctx.font=`800 ${size}px "Barlow Condensed", Impact, sans-serif`;lines=[];text.toUpperCase().split('\n').forEach(paragraph=>{let line='';paragraph.split(/\s+/).forEach(word=>{if(ctx.measureText(word).width>945){if(line){lines.push(line);line='';}let piece='';for(const c of word){if(ctx.measureText(piece+c).width>945){lines.push(piece);piece=c;}else piece+=c;}line=piece;}else if(line&&ctx.measureText(line+' '+word).width>945){lines.push(line);line=word;}else line+=(line?' ':'')+word;});lines.push(line);});if(lines.length*size*.96<=600)break;}const start=310+(600-lines.length*size*.96)/2;lines.forEach((line,i)=>ctx.fillText(line,60,start+i*size*.96));ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(65,960);ctx.lineTo(1015,960);ctx.stroke();ctx.font='20px "IBM Plex Mono", monospace';ctx.fillText('MAXIMUM INTELLIGENCE. MAXIMUM MEMES.',65,1010);ctx.textAlign='right';ctx.font='55px Arial';ctx.fillText('↗↗',1015,1020);ctx.textAlign='left';}
headline.addEventListener('input',renderPoster);
document.querySelectorAll('[data-theme]').forEach(b=>b.addEventListener('click',()=>{theme=b.dataset.theme;document.querySelectorAll('[data-theme]').forEach(item=>{item.classList.toggle('selected',item===b);item.setAttribute('aria-pressed',String(item===b));});renderPoster();}));
document.getElementById('download').addEventListener('click',()=>{renderPoster();canvas.toBlob(blob=>{if(!blob){notify('Export failed. Please try again.');return;}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='aimaxxi-transmission.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Your poster is ready.');},'image/png');});
renderPoster();document.fonts.ready.then(renderPoster);

let lastMetricTime=null;
async function refreshMetrics(){const button=document.getElementById('refresh-data'),status=document.getElementById('feed-status');button.disabled=true;button.textContent='Refreshing…';try{const response=await fetch('/api/metrics',{signal:AbortSignal.timeout(18000),cache:'no-store'});if(!response.ok)throw new Error('Unavailable');const data=await response.json();if(data.address!==address||!data.fetchedAt||!['sent','tokenPending','recipientPending'].every(k=>typeof data[k]==='string'))throw new Error('Invalid data');document.getElementById('fees-sent').textContent=data.sent;document.getElementById('token-pending').textContent=data.tokenPending;document.getElementById('recipient-pending').textContent=data.recipientPending;document.getElementById('payout-status').textContent=data.status;lastMetricTime=new Date(data.fetchedAt).toLocaleString();status.textContent=(data.stale?'STALE · LAST FETCH ':'USEPAID · FETCHED ')+lastMetricTime;}catch{status.textContent=lastMetricTime?'REFRESH UNAVAILABLE · LAST FETCH '+lastMetricTime:'REFRESH UNAVAILABLE · SCREENSHOT SNAPSHOT · 27 SEP 2026';}finally{button.disabled=false;button.textContent='Refresh data ↻';}}
document.getElementById('refresh-data').addEventListener('click',refreshMetrics);refreshMetrics();setInterval(()=>{if(!document.hidden)refreshMetrics();},60000);

let lastMarketFetch=null,marketBusy=false;
async function refreshMarket(){if(marketBusy)return;marketBusy=true;const status=document.getElementById('market-status');try{const response=await fetch('https://api.dexscreener.com/token-pairs/v1/solana/'+address,{signal:AbortSignal.timeout(12000),cache:'no-store'});if(!response.ok)throw new Error('Market unavailable');const pairs=await response.json();if(!Array.isArray(pairs))throw new Error('Invalid response');const valid=pairs.filter(p=>p.chainId==='solana'&&p.baseToken?.address===address&&Number.isFinite(Number(p.priceUsd))&&Number(p.priceUsd)>0&&Number.isFinite(p.liquidity?.usd)&&p.liquidity.usd>0);valid.sort((a,b)=>b.liquidity.usd-a.liquidity.usd);const pair=valid[0];if(!pair)throw new Error('No liquid matching pool');document.getElementById('token-price').textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumSignificantDigits:3,maximumSignificantDigits:5}).format(Number(pair.priceUsd));document.getElementById('market-cap').textContent=Number.isFinite(pair.marketCap)&&pair.marketCap>=0?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(pair.marketCap):'Unavailable';const change=pair.priceChange?.h24,changeEl=document.getElementById('price-change');changeEl.textContent=Number.isFinite(change)?(change>0?'+':'')+change.toFixed(2)+'% · 24h':'24h change unavailable';changeEl.style.color=Number.isFinite(change)?(change<0?'#ffb49f':'#d3fa49'):'';lastMarketFetch=new Date().toLocaleTimeString();status.textContent='DEXSCREENER · FETCHED '+lastMarketFetch+' · '+pair.dexId.toUpperCase()+' · 30s REFRESH';document.getElementById('dex-link').href='https://dexscreener.com/solana/'+encodeURIComponent(pair.pairAddress);}catch{status.textContent=lastMarketFetch?'DEXSCREENER · STALE · LAST FETCH '+lastMarketFetch:'DEXSCREENER · UNAVAILABLE · RETRYING AUTOMATICALLY';if(!lastMarketFetch)document.getElementById('price-change').textContent='Price temporarily unavailable';}finally{marketBusy=false;}}
refreshMarket();setInterval(()=>{if(!document.hidden)refreshMarket();},30000);document.getElementById('refresh-data').addEventListener('click',refreshMarket);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshMarket();});
